add run-hw target for easy hardware-based tests
Nitrokey/nitrokey-3-tests pull request #21
Opened 2023-03-21 11:39 UTC by daringer

2023-03-21 12:57 UTC, robin-nitrokey commented
Okay!  You could also just pass it through directly to the test suite and change `UsbDevice.find` to accept a list of UUIDs instead of a single UUID.  That would be more general.

https://github.com/Nitrokey/nitrokey-3-tests/blob/79ee739a4870f4b495d1916c8e404fb13399f805/conftest.py#L63
https://github.com/Nitrokey/nitrokey-3-tests/blob/79ee739a4870f4b495d1916c8e404fb13399f805/utils/device.py#L167

2023-03-22 07:57 UTC, robin-nitrokey requested changes
LGTM, but please add `variables.mk` to `.gitignore`.

2023-03-22 07:57 UTC, robin-nitrokey commented on Makefile
> +ALLOWED_UUIDS ?= NONE
Does this line have any effect?

2023-03-22 08:53 UTC, daringer commented on Makefile
> +ALLOWED_UUIDS ?= NONE
oopsy, debug artifact, removed

2023-03-22 19:55 UTC, robin-nitrokey approved these changes
Thanks!  Final request:  Please update the “Device selection” section in the README with the changed UUID flag and the new make target.

2023-03-23 11:37 UTC, daringer commented
mmmmh, docs, how about this one: 
https://github.com/Nitrokey/nitrokey-3-tests/pull/21/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R71-R78

2023-03-23 16:10 UTC, merged