Fix oct name change
Nitrokey/nitrokey-3-tests pull request #41
Opened 2024-04-25 09:38 UTC by sosthene-nitrokey

2024-04-25 11:43 UTC, robin-nitrokey requested changes
Please update the Dockerfile accordingly.

2024-04-25 19:24 UTC, robin-nitrokey commented on tests/basic.py
> +    dirname = "/tmp/tmp.qz0ExWLY7N"
Debugging artifact?

2024-04-26 07:26 UTC, robin-nitrokey approved these changes

2024-04-30 10:24 UTC, daringer approved these changes

2024-10-21 11:55 UTC, merged